config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'homes#index', as: 'root'
  get 'books' => 'books#index', as: 'books'
  post 'books' => 'books#create', as: 'create_book'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_book'
  patch 'books/:id' => 'books#update', as: 'update_book'
  delete 'books/:id' => 'books#destroy', as: 'destroy_book'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book  = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id),notice: 'Book was successfully created.'
    else
      @books = Book.all
      render :index
    end
  end
  
  def show
    @book = Book.find(params[:id])
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id),notice: 'Book was successfully updated.'
    else
      render :edit
    end
    
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path,notice: 'Book was successfully destroyed.'
  end
  
  
  private
  
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <div class="errors_box">
    <p class="errors_count"><%= @book.errors.count %> errors prohibited this book from being saved</p>
    <% @book.errors.full_messages.each do |message| %>
      <p>・<%= message %></p>
    <% end %>
  </div>
<% end %>
<%= form_with model:@book, url: update_book_path(@book.id), local: true do |f| %>
  <div>
    <%= f.label :title,'Title' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :body,'Body' %>
    <%= f.text_area :body %>
  </div>
  <div>
  <%= f.submit 'Update Book' %>
  </div>
<% end %>
<div>
  <%= link_to 'Show ',book_path(@book.id) %> | <%= link_to 'Back',books_path %>
</div>

app/views/books/index.html.erb
<% flash.each do |key,value| %>
  <%= content_tag(:p,value,class: key)%>
<% end %>
<h1 class="list_title">Books</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th></th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to 'Show ',book_path(book.id) %></td>
    <td><%= link_to 'Edit ',edit_book_path(book.id) %></td>
    <td><%= link_to 'Destroy' ,destroy_book_path(book.id),method: :delete %> </td>
  </tr>
  <% end %>
</table>

<h2 class="register_title">New book</h2>
<% if @book.errors.any? %>
  <div class="errors_box">
    <p class="errors_count"><%= @book.errors.count %> errors prohibited this book from being saved</p>
    <% @book.errors.full_messages.each do |message| %>
      <p>・<%= message %></p>
    <% end %>
  </div>
<% end %>
    
<%= form_with model:@book, url: create_book_path, local: true do |f| %>
  <div class="field">
    <%= f.label :title,'Title' %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body,'Body' %>
    <%= f.text_area :body %>
  </div>
  <div>
  <%= f.submit 'Create Book', class:'create_btn' %>
  </div>
<% end %>

app/views/books/show.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p,value,class: key) %>
<% end %>
<p class="m_33"><strong>Title:</strong><%= @book.title %></p> 
<p class="m_33"><strong>Body:</strong><%= @book.body %></p> 

<div>
  <%= link_to 'Edit',edit_book_path(@book.id) %> | <%= link_to 'Back',books_path %>
</div>

app/views/homes/index.html.erb
<h1>ようこそ <strong>Bookers</strong> へ！</h1>
<p class="m_33"><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p class="m_33">印象を共有し交換することができます</p>
<p class="m_33"><%= link_to "start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>